development:
  adapter: postgresql
  encoding: unicode
  database: make_companion
  pool: 5
  username: ericksanc
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: make_companion_test
  pool: 5
  username: ericksanc
  password:


# production:
#   adapter: postgresql
#   encoding: unicode
#   database: make_companion_production
#   pool: 5
#   username: postgres
#   password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['postgres://ywbxswvmivmttw:99b06fac1d4e3190cea57d4d9b18288a7d14054eafc6c1f848a6bdf52330c9de@ec2-54-204-43-7.compute-1.amazonaws.com:5432/d6grdiqi4ssa3'] %>
  username: <%= ENV['matthewharrilal@gmail.com'] %>
  password: <%= ENV['Latchman1'] %>
